name: kamus_investasi
description: Kamus Investasi.

publish_to: 'none'
version: 1.0.2+3

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  upgrader: ^6.2.0
  iconsax: ^0.0.8
  google_fonts: ^3.0.1
  sqflite: ^2.2.6
  intl: ^0.17.0
  fluttertoast: ^8.0.9
  path_provider: ^2.0.14
  infinite_scroll_pagination: ^3.2.0
  infinite_scroll: ^1.1.1
  change_app_package_name: ^1.1.0
  share_plus: ^4.0.8
  clipboard: ^0.1.3
  google_mobile_ads: ^2.4.0
  url_launcher: ^6.1.5
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/datasets/dictionaries.json
    - assets/images/bookmark.png
    - assets/images/history.png
    - assets/images/feedback.png

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
